import { runStrings } from "./src/strings/string.js";
import { runArrays } from "./src/arrays/array.js";
import { runObjects } from "./src/objects/object.js";
import { runNumbers } from "./src/numbers/number.js";
import { runMath } from "./src/math/math.js";
import { runDates } from "./src/dates/date.js";
import { runRegExp } from "./src/regexp/regexp.js";
import { runFunctions } from "./src/functions/function.js";
import { runJSON } from "./src/json/json.js";
import { runMaps } from "./src/maps/map.js";
import { runSets } from "./src/sets/set.js";
import { runWeakMap } from "./src/weakmap/weakmap.js";
import { runWeakSet } from "./src/weakset/weakset.js";
import { runPromises } from "./src/promises/promise.js";
import { runSymbols } from "./src/symbols/symbol.js";
import { runBigInt } from "./src/bigint/bigint.js";
import { runArrayBuffer } from "./src/array-buffer/array-buffer.js";
import { runTypedArrays } from "./src/typed-arrays/typed-arrays.js";
import { runIterators } from "./src/iterators/iterator.js";
import { runErrors } from "./src/errors/error.js";
import { runIntl } from "./src/intl/intl.js";
import { runReflect } from "./src/reflect/reflect.js";
import { runProxy } from "./src/proxy/proxy.js";
import { runWeakRef } from "./src/weak-ref/weak-ref.js";
import { runFinalizationRegistry } from "./src/finalization-registry/finalization-registry.js";

console.log("JavaScript Built-in Methods Reference (Node 24+)");
runStrings(); runArrays(); runObjects(); runNumbers(); runMath(); runDates(); runRegExp(); runFunctions(); runJSON(); runMaps(); runSets(); runWeakMap(); runWeakSet(); await runPromises(); await runSymbols(); runBigInt(); runArrayBuffer(); runTypedArrays(); runIterators(); runErrors(); runIntl(); runReflect(); runProxy(); runWeakRef(); runFinalizationRegistry();
